on: [pull_request, push]
jobs:
    deploy:
      name: deploy
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v4
      - name: Setup NodeJs
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
      - name: Running install
        run: 
          npm install
      - name: Running build
        run:
          npm run tw-start
      - name: Deploy finished sucessfully!
        run: 
          echo "Sucessfully passed tests."
